version: "3"
services:
  user-service:
    build:
      context: .
    image: maven/builder:user-service
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=user-service
      - POSTGRES_PASSWORD=user-service
      - POSTGRES_DB=user
    volumes:
      - "./src:/build/src"
      - "./target:/build/target:cached"
    command: "mvn spring-boot:run"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - my-application-network

  postgres:
    image: postgres
    container_name: postgres-user
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-service
      POSTGRES_PASSWORD: user-service
      POSTGRES_DB: user
    networks:
      - my-application-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - my-application-network

networks:
  my-application-network:
    driver: bridge