spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    username: user-service
    password: user-service
    url: jdbc:postgresql://localhost:5432/user
  rabbitmq:
    template:
      exchange-create: user.create
      exchange-update: user.update
      exchange-delete: user.delete

jwt:
  secret: G+KbPeShVmYq3t6w9z$C&F)J@McQfTjW
  duration: 12h
