spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    username: user-service
    password: user-service
    url: jdbc:postgresql://postgres-user:5432/user
  rabbitmq:
    template:
      exchange-create: user.create
      exchange-update: user.update
      exchange-delete: user.delete
      exchange-activation: user.activation
    host: rabbitmq-server

jwt:
  secret: G+KbPeShVmYq3t6w9z$C&F)J@McQfTjW
  duration: 12h
